// Question bank — Maharashtra State Board (SSC) syllabus, Classes 8-10
// Subjects covered in the knowledge section: Science, Maths, English, Computer/Tech
// type: "likert" (1-5) | "mcq_behaviour" (single choice) | "ai_readiness" (single choice)
// | "mcq" (single-answer knowledge question, scored) | "mcq_multi" (MULTIPLE correct options, scored)
// | "text" (open answer)
// Total per standard = 10 likert + 5 behaviour + 4 AI + 20 knowledge MCQs (5/subject) + 3 text = 42

const SECTION_A_LIKERT = [
  { id: "a1", concept: "engagement", en: "I enjoy learning new subjects in school.", hi: "मुझे स्कूल में नए विषय सीखना अच्छा लगता है।", mr: "मला शाळेत नवीन विषय शिकायला आवडतं." },
  { id: "a2", concept: "engagement", en: "I understand what is taught in class easily.", hi: "मुझे क्लास में पढ़ाई गई बातें आसानी से समझ आती हैं।", mr: "मला वर्गात शिकवलेलं सहज समजतं." },
  { id: "a3", concept: "engagement", en: "I can remember concepts after the class is over.", hi: "क्लास खत्म होने के बाद भी मुझे बातें याद रहती हैं।", mr: "वर्ग संपल्यावरही मला गोष्टी लक्षात राहतात." },
  { id: "a4", concept: "confidence", en: "I feel confident while answering questions in exams.", hi: "परीक्षा में सवालों के जवाब देते समय मुझे आत्मविश्वास महसूस होता है।", mr: "परीक्षेत प्रश्नांची उत्तरं देताना मला आत्मविश्वास वाटतो." },
  { id: "a5", concept: "engagement", en: "I ask my teacher whenever I have a doubt.", hi: "जब भी मुझे शंका होती है, मैं अपने शिक्षक से पूछता/पूछती हूं।", mr: "जेव्हा शंका असते तेव्हा मी शिक्षकांना विचारतो/विचारते." },
  { id: "a6", concept: "engagement", en: "I revise my lessons regularly.", hi: "मैं नियमित रूप से अपने पाठ दोहराता/दोहराती हूं।", mr: "मी नियमितपणे धड्यांची उजळणी करतो/करते." },
  { id: "a7", concept: "practical", en: "Practicals/experiments and activities help me understand better.", hi: "प्रयोग और गतिविधियां मुझे बेहतर समझने में मदद करती हैं।", mr: "प्रयोग आणि उपक्रम मला अधिक चांगल्या समजायला मदत करतात." },
  { id: "a8", concept: "practical", en: "I enjoy hands-on activities in class (labs, computer, drawing, etc.).", hi: "मुझे क्लास में व्यावहारिक गतिविधियां (लैब, कंप्यूटर, ड्राइंग आदि) करना अच्छा लगता है।", mr: "मला वर्गात प्रात्यक्षिक उपक्रम (लॅब, संगणक, चित्रकला इ.) करायला आवडतं." },
  { id: "a9", concept: "confidence", en: "I feel stressed during exams.", hi: "परीक्षा के दौरान मुझे तनाव महसूस होता है।", mr: "परीक्षेच्या वेळी मला ताण जाणवतो." },
  { id: "a10", concept: "confidence", en: "I believe I can score good marks this year.", hi: "मुझे विश्वास है कि मैं इस साल अच्छे अंक ला सकता/सकती हूं।", mr: "मला विश्वास आहे की मी यंदा चांगले गुण मिळवू शकतो/शकते." }
];

const SECTION_C_AI = [
  { id: "c1", en: "Have you heard about Artificial Intelligence (AI) before?", hi: "क्या तुमने पहले कभी आर्टिफिशियल इंटेलिजेंस (AI) के बारे में सुना है?", mr: "तुम्ही याआधी आर्टिफिशियल इंटेलिजन्स (AI) बद्दल ऐकलं आहे का?", options: ["yes", "no"] },
  { id: "c2", en: "Would you use an app that helps you understand your subjects better using AI?", hi: "क्या तुम एक ऐसा ऐप इस्तेमाल करना चाहोगे जो AI से विषय समझने में मदद करे?", mr: "AI वापरून विषय समजायला मदत करणारं ॲप तुम्ही वापराल का?", options: ["yes", "no", "maybe"] },
  { id: "c3", en: "Which feature would help you the most?", hi: "कौन सी सुविधा तुम्हें सबसे ज्यादा मदद करेगी?", mr: "कोणती सुविधा तुम्हाला सर्वात जास्त मदत करेल?", options: ["Video Explanation", "Notes", "Quiz Practice", "Doubt Solving", "Personalized Study Plan"] },
  { id: "c4", en: "Would you like the app to point out exactly which topics you are weak in?", hi: "क्या तुम चाहोगे कि ऐप बताए कि तुम किन विषयों में कमज़ोर हो?", mr: "ॲपने तुम्ही कोणत्या विषयांत कच्चे आहात हे नेमकं सांगावं असं तुम्हाला वाटतं का?", options: ["yes", "no"] }
];

const SECTION_E_TEXT = [
  { id: "e1", en: "What is the biggest challenge you face while studying?", hi: "पढ़ाई करते समय तुम्हें सबसे बड़ी चुनौती क्या लगती है?", mr: "अभ्यास करताना तुम्हाला सर्वात मोठं आव्हान काय वाटतं?" },
  { id: "e2", en: "If you could improve one thing about your school classes, what would it be?", hi: "अगर तुम अपनी स्कूल की कक्षाओं में एक चीज़ बदल सकते, तो वह क्या होगी?", mr: "जर तुम्ही तुमच्या शाळेतील वर्गातील एक गोष्ट बदलू शकलात, तर ती कोणती असेल?" },
  { id: "e3", en: "Would you recommend an AI learning app to your friends?", hi: "क्या तुम अपने दोस्तों को एक AI लर्निंग ऐप सुझाओगे?", mr: "तुम्ही तुमच्या मित्रांना AI लर्निंग ॲप सुचवाल का?" }
];

function sectionB(chapters) {
  return [
    { id: "b1", en: "Which subject is most difficult for you?", hi: "कौन सा विषय तुम्हारे लिए सबसे कठिन है?", mr: "कोणता विषय तुमच्यासाठी सर्वात अवघड आहे?", options: ["Science", "Maths", "English", "Computer/Tech"] },
    { id: "b2", en: "Which topic do you find hardest?", hi: "कौन सा विषय तुम्हें सबसे कठिन लगता है?", mr: "कोणता विषय तुम्हाला सर्वात अवघड वाटतो?", options: chapters },
    { id: "b3", en: "Why do you find it difficult?", hi: "तुम्हें यह कठिन क्यों लगता है?", mr: "तुम्हाला हे अवघड का वाटतं?", options: ["Difficult concepts", "Difficult language/words", "Lack of practice", "Teaching is too fast", "I hesitate to ask doubts", "I forget concepts quickly"] },
    { id: "b4", en: "When you don't understand a topic, what do you usually do?", hi: "जब कोई विषय समझ नहीं आता, तो तुम आमतौर पर क्या करते हो?", mr: "एखादा विषय समजत नाही तेव्हा तुम्ही सहसा काय करता?", options: ["Ask teacher", "Ask friend", "Search on YouTube", "Search on Google", "Leave it / ignore it"] },
    { id: "b5", en: "Which way of learning helps you the most?", hi: "कौन सा तरीका तुम्हें सीखने में सबसे ज्यादा मदद करता है?", mr: "कोणती शिकण्याची पद्धत तुम्हाला सर्वात जास्त मदत करते?", options: ["Practical experiments", "Videos", "Teacher's explanation", "Reading the textbook", "Group discussion"] }
  ];
}

// ---------------- Knowledge MCQ banks (5 per subject per standard = 20 per standard) ----------------
// difficulty: basic | medium | hard   |   type: "mcq" (single) or "mcq_multi" (multiple correct)

const MCQ_8 = [
  // Science (5)
  { subject: "Science", concept: "Force and Pressure", chapter: "Force and Pressure", difficulty: "basic", type: "mcq", en: "When you push or pull an object, what are you applying?", hi: "जब तुम किसी वस्तु को धकेलते या खींचते हो, तो तुम क्या लगाते हो?", mr: "तुम्ही एखाद्या वस्तूला ढकलता किंवा ओढता तेव्हा तुम्ही काय लावता?", options: ["Energy", "Force", "Heat", "Pressure"], answer: "Force" },
  { subject: "Science", concept: "Friction", chapter: "Friction", difficulty: "medium", type: "mcq", en: "Which of these reduces friction the most?", hi: "इनमें से कौन सा घर्षण को सबसे ज्यादा कम करता है?", mr: "यापैकी काय घर्षण सर्वात जास्त कमी करते?", options: ["Rough surface", "Oil/lubricant", "Increasing weight", "Sandpaper"], answer: "Oil/lubricant" },
  { subject: "Science", concept: "Combustion and Flame", chapter: "Combustion and Flame", difficulty: "basic", type: "mcq", en: "For combustion (burning) to occur, which gas is essential?", hi: "दहन (जलने) के लिए कौन सी गैस आवश्यक है?", mr: "ज्वलनासाठी कोणता वायू आवश्यक असतो?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: "Oxygen" },
  { subject: "Science", concept: "Cell Structure", chapter: "Cell Structure and Microorganisms", difficulty: "medium", type: "mcq_multi", en: "Which of these are found in a plant cell? (Select all that apply)", hi: "इनमें से कौन सी संरचनाएं पौधों की कोशिका में पाई जाती हैं? (सभी सही विकल्प चुनें)", mr: "यापैकी कोणत्या रचना वनस्पती पेशीत आढळतात? (सर्व योग्य पर्याय निवडा)", options: ["Cell wall", "Nucleus", "Chloroplast", "Cell membrane"], answers: ["Cell wall", "Nucleus", "Chloroplast", "Cell membrane"] },
  { subject: "Science", concept: "Metals and Non-metals", chapter: "Metals and Non-metals", difficulty: "basic", type: "mcq", en: "Which of these is a good conductor of electricity?", hi: "इनमें से कौन बिजली का अच्छा चालक है?", mr: "यापैकी वीज वाहून नेणारा चांगला पदार्थ कोणता?", options: ["Copper", "Rubber", "Wood", "Plastic"], answer: "Copper" },
  // Maths (5)
  { subject: "Maths", concept: "Rational Numbers", chapter: "Rational Numbers", difficulty: "basic", type: "mcq", en: "Which of these is a rational number?", hi: "इनमें से कौन सी एक परिमेय संख्या है?", mr: "यापैकी कोणती एक परिमेय संख्या आहे?", options: ["3/4", "√2", "π", "None"], answer: "3/4" },
  { subject: "Maths", concept: "Linear Equations", chapter: "Linear Equations in One Variable", difficulty: "medium", type: "mcq", en: "If 2x + 4 = 12, what is x?", hi: "अगर 2x + 4 = 12 है, तो x का मान क्या है?", mr: "जर 2x + 4 = 12 असेल, तर x किती?", options: ["4", "6", "8", "2"], answer: "4" },
  { subject: "Maths", concept: "Squares and Cubes", chapter: "Squares and Square Roots", difficulty: "basic", type: "mcq", en: "What is the square of 12?", hi: "12 का वर्ग क्या है?", mr: "12 चा वर्ग किती?", options: ["144", "124", "132", "121"], answer: "144" },
  { subject: "Maths", concept: "Mensuration", chapter: "Mensuration", difficulty: "medium", type: "mcq", en: "The formula for the area of a rectangle is?", hi: "आयत के क्षेत्रफल का सूत्र क्या है?", mr: "आयताच्या क्षेत्रफळाचं सूत्र काय?", options: ["Length × Breadth", "2(Length+Breadth)", "Side × Side", "½ × base × height"], answer: "Length × Breadth" },
  { subject: "Maths", concept: "Data Handling", chapter: "Data Handling", difficulty: "hard", type: "mcq", en: "The middle value of a data set arranged in order is called the?", hi: "क्रम में व्यवस्थित डेटा सेट का मध्य मान क्या कहलाता है?", mr: "क्रमाने मांडलेल्या माहिती संचाचं मधलं मूल्य काय म्हणतात?", options: ["Median", "Mode", "Range", "Mean only"], answer: "Median" },
  // English (5)
  { subject: "English", concept: "Parts of Speech", chapter: "Grammar Basics", difficulty: "basic", type: "mcq", en: "Which word is a noun in this sentence: 'The dog ran quickly'?", hi: "इस वाक्य में कौन सा शब्द संज्ञा है: 'The dog ran quickly'?", mr: "या वाक्यात कोणता शब्द नाम आहे: 'The dog ran quickly'?", options: ["dog", "ran", "quickly", "the"], answer: "dog" },
  { subject: "English", concept: "Tenses", chapter: "Tenses", difficulty: "medium", type: "mcq", en: "Choose the correct past tense of 'go'.", hi: "'go' का सही भूतकाल चुनो।", mr: "'go' चा योग्य भूतकाळ निवडा.", options: ["goed", "gone", "went", "going"], answer: "went" },
  { subject: "English", concept: "Synonyms", chapter: "Vocabulary", difficulty: "basic", type: "mcq", en: "Choose the synonym of 'Happy'.", hi: "'Happy' का समानार्थी शब्द चुनो।", mr: "'Happy' चा समानार्थी शब्द निवडा.", options: ["Sad", "Joyful", "Angry", "Tired"], answer: "Joyful" },
  { subject: "English", concept: "Articles", chapter: "Articles", difficulty: "medium", type: "mcq", en: "Fill in the blank: 'She is ___ honest girl.'", hi: "खाली स्थान भरो: 'She is ___ honest girl.'", mr: "रिकामी जागा भरा: 'She is ___ honest girl.'", options: ["a", "an", "the", "no article needed"], answer: "an" },
  { subject: "English", concept: "Prepositions", chapter: "Prepositions", difficulty: "medium", type: "mcq", en: "Choose the correct preposition: 'The book is ___ the table.'", hi: "सही पूर्वसर्ग (preposition) चुनो: 'The book is ___ the table.'", mr: "योग्य प्रीपोझिशन निवडा: 'The book is ___ the table.'", options: ["on", "in", "at", "by"], answer: "on" },
  // Computer / Tech (5)
  { subject: "Computer", concept: "Hardware vs Software", chapter: "Computer Basics", difficulty: "basic", type: "mcq", en: "Which of these is an example of hardware?", hi: "इनमें से कौन हार्डवेयर का उदाहरण है?", mr: "यापैकी हार्डवेअरचं उदाहरण कोणतं?", options: ["Keyboard", "MS Word", "Windows", "Antivirus"], answer: "Keyboard" },
  { subject: "Computer", concept: "Input/Output Devices", chapter: "Computer Basics", difficulty: "basic", type: "mcq_multi", en: "Which of these are INPUT devices? (Select all that apply)", hi: "इनमें से कौन से इनपुट डिवाइस हैं? (सभी सही विकल्प चुनें)", mr: "यापैकी कोणती इनपुट उपकरणं आहेत? (सर्व योग्य पर्याय निवडा)", options: ["Keyboard", "Mouse", "Monitor", "Scanner"], answers: ["Keyboard", "Mouse", "Scanner"] },
  { subject: "Computer", concept: "Internet Basics", chapter: "Internet Basics", difficulty: "medium", type: "mcq", en: "What does 'www' stand for?", hi: "'www' का पूर्ण रूप क्या है?", mr: "'www' चा पूर्ण अर्थ काय?", options: ["World Wide Web", "World Web Wide", "Web World Wide", "Wide World Web"], answer: "World Wide Web" },
  { subject: "Computer", concept: "MS Word Basics", chapter: "Office Software", difficulty: "medium", type: "mcq", en: "Which software is mainly used to write and format documents?", hi: "दस्तावेज़ लिखने और फॉर्मेट करने के लिए मुख्य रूप से किस सॉफ्टवेयर का उपयोग होता है?", mr: "कागदपत्रं लिहिण्यासाठी आणि फॉरमॅट करण्यासाठी प्रामुख्याने कोणतं सॉफ्टवेअर वापरलं जातं?", options: ["MS Word", "MS Paint", "Calculator", "VLC Player"], answer: "MS Word" },
  { subject: "Computer", concept: "Keyboard Shortcuts", chapter: "Computer Basics", difficulty: "hard", type: "mcq", en: "Which shortcut key is used to copy selected text?", hi: "चुने गए टेक्स्ट को कॉपी करने के लिए कौन सी शॉर्टकट कुंजी उपयोग होती है?", mr: "निवडलेला मजकूर कॉपी करण्यासाठी कोणती शॉर्टकट की वापरली जाते?", options: ["Ctrl+C", "Ctrl+V", "Ctrl+X", "Ctrl+Z"], answer: "Ctrl+C" }
];

const MCQ_9 = [
  // Science (5)
  { subject: "Science", concept: "Motion", chapter: "Motion", difficulty: "basic", type: "mcq", en: "The distance travelled by an object per unit time is called its?", hi: "किसी वस्तु द्वारा प्रति इकाई समय में तय की गई दूरी को क्या कहते हैं?", mr: "एखाद्या वस्तूने प्रति एकक वेळेत कापलेल्या अंतराला काय म्हणतात?", options: ["Speed", "Force", "Mass", "Pressure"], answer: "Speed" },
  { subject: "Science", concept: "Gravitation", chapter: "Gravitation", difficulty: "basic", type: "mcq", en: "The force that pulls objects towards the Earth is called?", hi: "वह बल जो वस्तुओं को पृथ्वी की ओर खींचता है, उसे क्या कहते हैं?", mr: "वस्तूंना पृथ्वीकडे ओढणाऱ्या बलाला काय म्हणतात?", options: ["Gravity", "Friction", "Magnetism", "Tension"], answer: "Gravity" },
  { subject: "Science", concept: "Atoms and Molecules", chapter: "Atoms and Molecules", difficulty: "medium", type: "mcq", en: "The smallest particle of an element that can take part in a chemical reaction is called?", hi: "किसी तत्व का सबसे छोटा कण जो रासायनिक अभिक्रिया में भाग ले सकता है, उसे क्या कहते हैं?", mr: "मूलद्रव्याचा सर्वात लहान कण जो रासायनिक अभिक्रियेत भाग घेऊ शकतो त्याला काय म्हणतात?", options: ["Atom", "Molecule", "Ion only", "Cell"], answer: "Atom" },
  { subject: "Science", concept: "Cell", chapter: "Fundamental Unit of Life", difficulty: "medium", type: "mcq_multi", en: "Which of these are parts of a cell? (Select all that apply)", hi: "इनमें से कौन सी कोशिका के भाग हैं? (सभी सही विकल्प चुनें)", mr: "यापैकी कोणते पेशीचे भाग आहेत? (सर्व योग्य पर्याय निवडा)", options: ["Nucleus", "Cytoplasm", "Mitochondria", "Photosynthesis"], answers: ["Nucleus", "Cytoplasm", "Mitochondria"] },
  { subject: "Science", concept: "Natural Resources", chapter: "Natural Resources", difficulty: "basic", type: "mcq", en: "The layer of gases surrounding the Earth is called the?", hi: "पृथ्वी के चारों ओर गैसों की परत को क्या कहते हैं?", mr: "पृथ्वीभोवती असलेल्या वायूंच्या थराला काय म्हणतात?", options: ["Atmosphere", "Hydrosphere", "Lithosphere", "Biosphere only"], answer: "Atmosphere" },
  // Maths (5)
  { subject: "Maths", concept: "Number Systems", chapter: "Number Systems", difficulty: "medium", type: "mcq", en: "√2 is an example of which type of number?", hi: "√2 किस प्रकार की संख्या का उदाहरण है?", mr: "√2 कोणत्या प्रकारच्या संख्येचं उदाहरण आहे?", options: ["Rational", "Irrational", "Whole", "Natural"], answer: "Irrational" },
  { subject: "Maths", concept: "Polynomials", chapter: "Polynomials", difficulty: "medium", type: "mcq", en: "What is the degree of the polynomial 3x² + 5x + 2?", hi: "बहुपद 3x² + 5x + 2 की घात (degree) क्या है?", mr: "3x² + 5x + 2 या बहुपदीचा घात किती?", options: ["1", "2", "3", "5"], answer: "2" },
  { subject: "Maths", concept: "Coordinate Geometry", chapter: "Coordinate Geometry", difficulty: "basic", type: "mcq", en: "The point where the x-axis and y-axis meet is called the?", hi: "जहां x-अक्ष और y-अक्ष मिलते हैं, उसे क्या कहते हैं?", mr: "जिथे x-अक्ष आणि y-अक्ष भेटतात त्याला काय म्हणतात?", options: ["Origin", "Quadrant", "Intercept", "Coordinate"], answer: "Origin" },
  { subject: "Maths", concept: "Linear Equations", chapter: "Linear Equations in Two Variables", difficulty: "hard", type: "mcq", en: "How many solutions does a linear equation in two variables generally have?", hi: "दो चरों वाले एक रैखिक समीकरण के आमतौर पर कितने हल होते हैं?", mr: "दोन चलांच्या रेषीय समीकरणाला साधारणपणे किती उत्तरं असतात?", options: ["Exactly one", "Infinitely many", "Exactly two", "None"], answer: "Infinitely many" },
  { subject: "Maths", concept: "Statistics", chapter: "Statistics", difficulty: "basic", type: "mcq", en: "The most frequently occurring value in a data set is called the?", hi: "किसी डेटा सेट में सबसे अधिक बार आने वाला मान क्या कहलाता है?", mr: "माहिती संचात सर्वात जास्त वेळा येणाऱ्या मूल्याला काय म्हणतात?", options: ["Mode", "Median", "Mean", "Range"], answer: "Mode" },
  // English (5)
  { subject: "English", concept: "Tenses", chapter: "Tenses", difficulty: "medium", type: "mcq", en: "Choose the correct sentence in present continuous tense.", hi: "वर्तमान निरंतर काल (present continuous) में सही वाक्य चुनो।", mr: "वर्तमान चालू काळातील (present continuous) योग्य वाक्य निवडा.", options: ["She plays cricket.", "She is playing cricket.", "She played cricket.", "She will play cricket."], answer: "She is playing cricket." },
  { subject: "English", concept: "Active-Passive Voice", chapter: "Voice", difficulty: "hard", type: "mcq", en: "Which is the passive form of 'The teacher teaches the class'?", hi: "'The teacher teaches the class' का कर्मवाच्य (passive) रूप कौन सा है?", mr: "'The teacher teaches the class' चं कर्मणी (passive) रूप कोणतं?", options: ["The class teaches the teacher.", "The class is taught by the teacher.", "The teacher is teaching.", "The class was teaching."], answer: "The class is taught by the teacher." },
  { subject: "English", concept: "Prepositions", chapter: "Prepositions", difficulty: "medium", type: "mcq", en: "Choose the correct preposition: 'He is good ___ Maths.'", hi: "सही पूर्वसर्ग चुनो: 'He is good ___ Maths.'", mr: "योग्य प्रीपोझिशन निवडा: 'He is good ___ Maths.'", options: ["at", "in", "on", "for"], answer: "at" },
  { subject: "English", concept: "Vocabulary", chapter: "Vocabulary", difficulty: "basic", type: "mcq", en: "Choose the antonym of 'Difficult'.", hi: "'Difficult' का विलोम शब्द चुनो।", mr: "'Difficult' चा विरुद्धार्थी शब्द निवडा.", options: ["Easy", "Hard", "Complex", "Tough"], answer: "Easy" },
  { subject: "English", concept: "Punctuation", chapter: "Punctuation", difficulty: "basic", type: "mcq", en: "Which punctuation mark is used to end a question?", hi: "प्रश्न को समाप्त करने के लिए किस विराम चिह्न का उपयोग होता है?", mr: "प्रश्न संपवण्यासाठी कोणतं विरामचिन्ह वापरलं जातं?", options: ["Full stop", "Question mark", "Comma", "Exclamation mark"], answer: "Question mark" },
  // Computer / Tech (5)
  { subject: "Computer", concept: "Networking Basics", chapter: "Networking", difficulty: "medium", type: "mcq", en: "A network limited to a small area like a school or office is called?", hi: "स्कूल या ऑफिस जैसे छोटे क्षेत्र तक सीमित नेटवर्क को क्या कहते हैं?", mr: "शाळा किंवा कार्यालयासारख्या लहान क्षेत्रापुरतं मर्यादित नेटवर्क काय म्हणतात?", options: ["LAN", "WAN", "MAN", "Internet"], answer: "LAN" },
  { subject: "Computer", concept: "Software Types", chapter: "Software", difficulty: "basic", type: "mcq_multi", en: "Which of these are examples of application software? (Select all that apply)", hi: "इनमें से कौन से एप्लिकेशन सॉफ्टवेयर के उदाहरण हैं? (सभी सही विकल्प चुनें)", mr: "यापैकी कोणती ॲप्लिकेशन सॉफ्टवेअरची उदाहरणं आहेत? (सर्व योग्य पर्याय निवडा)", options: ["MS Word", "Windows OS", "MS Excel", "Chrome Browser"], answers: ["MS Word", "MS Excel", "Chrome Browser"] },
  { subject: "Computer", concept: "Spreadsheet Basics", chapter: "Spreadsheets", difficulty: "medium", type: "mcq", en: "In MS Excel, a single box where you enter data is called a?", hi: "MS Excel में, जिस एक बॉक्स में डेटा डाला जाता है, उसे क्या कहते हैं?", mr: "MS Excel मध्ये, डेटा टाकण्यासाठी असलेल्या एका चौकोनाला काय म्हणतात?", options: ["Cell", "Row", "Sheet", "Column"], answer: "Cell" },
  { subject: "Computer", concept: "Algorithms", chapter: "Introduction to Coding", difficulty: "hard", type: "mcq", en: "A step-by-step set of instructions to solve a problem is called an?", hi: "किसी समस्या को हल करने के लिए चरण-दर-चरण निर्देशों के समूह को क्या कहते हैं?", mr: "एखादी समस्या सोडवण्यासाठी टप्प्याटप्प्याने दिलेल्या सूचनांच्या संचाला काय म्हणतात?", options: ["Algorithm", "Browser", "Operating System", "Database"], answer: "Algorithm" },
  { subject: "Computer", concept: "Cyber Safety", chapter: "Cyber Safety", difficulty: "basic", type: "mcq", en: "What should you do if a stranger online asks for your personal details?", hi: "अगर ऑनलाइन कोई अजनबी तुम्हारी निजी जानकारी मांगे तो तुम्हें क्या करना चाहिए?", mr: "जर ऑनलाइन एखादा अनोळखी व्यक्ती तुमची वैयक्तिक माहिती मागत असेल तर तुम्ही काय करावं?", options: ["Share it politely", "Refuse and tell a trusted adult", "Ignore and continue chatting", "Share only your school name"], answer: "Refuse and tell a trusted adult" }
];

const MCQ_10 = [
  // Science (5)
  { subject: "Science", concept: "Chemical Reactions", chapter: "Chemical Reactions and Equations", difficulty: "basic", type: "mcq", en: "Rusting of iron is an example of a?", hi: "लोहे में जंग लगना किसका उदाहरण है?", mr: "लोखंडाला गंज लागणे हे कशाचं उदाहरण आहे?", options: ["Oxidation reaction", "Reduction only", "Neutralization", "Displacement only"], answer: "Oxidation reaction" },
  { subject: "Science", concept: "Acids Bases Salts", chapter: "Acids, Bases and Salts", difficulty: "basic", type: "mcq", en: "The pH of a neutral solution (pure water) is?", hi: "एक उदासीन घोल (शुद्ध जल) का pH क्या होता है?", mr: "उदासीन द्रावणाचा (शुद्ध पाणी) pH किती असतो?", options: ["7", "0", "14", "10"], answer: "7" },
  { subject: "Science", concept: "Life Processes", chapter: "Life Processes", difficulty: "medium", type: "mcq_multi", en: "Which of these are involved in the process of photosynthesis? (Select all that apply)", hi: "इनमें से कौन प्रकाश संश्लेषण की प्रक्रिया में शामिल हैं? (सभी सही विकल्प चुनें)", mr: "यापैकी कोणते प्रकाशसंश्लेषणाच्या प्रक्रियेत सामील आहेत? (सर्व योग्य पर्याय निवडा)", options: ["Sunlight", "Carbon Dioxide", "Chlorophyll", "Nitrogen gas"], answers: ["Sunlight", "Carbon Dioxide", "Chlorophyll"] },
  { subject: "Science", concept: "Light", chapter: "Light - Reflection and Refraction", difficulty: "basic", type: "mcq", en: "The bending of light as it passes from one medium to another is called?", hi: "प्रकाश का एक माध्यम से दूसरे माध्यम में जाते समय मुड़ना क्या कहलाता है?", mr: "प्रकाश एका माध्यमातून दुसऱ्या माध्यमात जाताना वाकण्याला काय म्हणतात?", options: ["Refraction", "Reflection only", "Dispersion only", "Diffraction only"], answer: "Refraction" },
  { subject: "Science", concept: "Electricity", chapter: "Electricity", difficulty: "medium", type: "mcq", en: "Ohm's Law relates voltage, current and?", hi: "ओम का नियम वोल्टेज, धारा और किसके बीच संबंध बताता है?", mr: "ओहमचा नियम व्होल्टेज, प्रवाह आणि कशाचा संबंध सांगतो?", options: ["Resistance", "Power only", "Energy only", "Frequency"], answer: "Resistance" },
  // Maths (5)
  { subject: "Maths", concept: "Real Numbers", chapter: "Real Numbers", difficulty: "medium", type: "mcq", en: "The HCF of two numbers is found using which method commonly?", hi: "दो संख्याओं का HCF आमतौर पर किस विधि से निकाला जाता है?", mr: "दोन संख्यांचा म.सा.वि. सहसा कोणत्या पद्धतीने काढला जातो?", options: ["Euclid's Division Algorithm", "Pythagoras Theorem", "Quadratic Formula", "Venn Diagram"], answer: "Euclid's Division Algorithm" },
  { subject: "Maths", concept: "Quadratic Equations", chapter: "Quadratic Equations", difficulty: "hard", type: "mcq", en: "The standard form of a quadratic equation is?", hi: "द्विघात समीकरण का मानक रूप क्या है?", mr: "वर्गसमीकरणाचं प्रमाणित रूप काय आहे?", options: ["ax² + bx + c = 0", "ax + b = 0", "a/x + b = 0", "ax³ + b = 0"], answer: "ax² + bx + c = 0" },
  { subject: "Maths", concept: "Trigonometry", chapter: "Introduction to Trigonometry", difficulty: "medium", type: "mcq", en: "What is the value of sin(90°)?", hi: "sin(90°) का मान क्या है?", mr: "sin(90°) चं मूल्य किती?", options: ["0", "1", "½", "Undefined"], answer: "1" },
  { subject: "Maths", concept: "Circles", chapter: "Circles", difficulty: "basic", type: "mcq", en: "A line that touches a circle at exactly one point is called a?", hi: "जो रेखा किसी वृत्त को केवल एक बिंदु पर स्पर्श करती है, उसे क्या कहते हैं?", mr: "जी रेषा वर्तुळाला फक्त एका बिंदूत स्पर्श करते तिला काय म्हणतात?", options: ["Tangent", "Secant", "Chord", "Diameter"], answer: "Tangent" },
  { subject: "Maths", concept: "Statistics", chapter: "Statistics", difficulty: "medium", type: "mcq", en: "The sum of all values divided by the number of values gives the?", hi: "सभी मानों के योग को मानों की संख्या से भाग देने पर क्या प्राप्त होता है?", mr: "सर्व मूल्यांची बेरीज मूल्यांच्या संख्येने भागल्यास काय मिळतं?", options: ["Mean", "Mode", "Median", "Range"], answer: "Mean" },
  // English (5)
  { subject: "English", concept: "Tenses and Modals", chapter: "Modals", difficulty: "medium", type: "mcq", en: "Choose the correct modal: 'You ___ finish your homework before playing.'", hi: "सही मोडल चुनो: 'You ___ finish your homework before playing.'", mr: "योग्य मोडल निवडा: 'You ___ finish your homework before playing.'", options: ["must", "may", "can", "could"], answer: "must" },
  { subject: "English", concept: "Figures of Speech", chapter: "Figures of Speech", difficulty: "hard", type: "mcq", en: "'The stars danced in the sky' is an example of?", hi: "'The stars danced in the sky' किसका उदाहरण है?", mr: "'The stars danced in the sky' हे कशाचं उदाहरण आहे?", options: ["Personification", "Simile", "Alliteration", "Rhyme"], answer: "Personification" },
  { subject: "English", concept: "Vocabulary", chapter: "Vocabulary", difficulty: "basic", type: "mcq", en: "Choose the synonym of 'Enormous'.", hi: "'Enormous' का समानार्थी शब्द चुनो।", mr: "'Enormous' चा समानार्थी शब्द निवडा.", options: ["Tiny", "Huge", "Quick", "Weak"], answer: "Huge" },
  { subject: "English", concept: "Articles and Prepositions", chapter: "Grammar", difficulty: "medium", type: "mcq", en: "Fill in the blank: 'He is interested ___ Science.'", hi: "खाली स्थान भरो: 'He is interested ___ Science.'", mr: "रिकामी जागा भरा: 'He is interested ___ Science.'", options: ["in", "at", "on", "for"], answer: "in" },
  { subject: "English", concept: "Reading Comprehension", chapter: "Comprehension", difficulty: "medium", type: "mcq", en: "A summary that captures the main idea of a passage in your own words is called a?", hi: "किसी गद्यांश के मुख्य विचार को अपने शब्दों में बताना क्या कहलाता है?", mr: "एखाद्या उताऱ्यातील मुख्य कल्पना स्वतःच्या शब्दांत मांडणं याला काय म्हणतात?", options: ["Paraphrase/Summary", "Plagiarism", "Quotation", "Footnote"], answer: "Paraphrase/Summary" },
  // Computer / Tech (5)
  { subject: "Computer", concept: "Programming Basics", chapter: "Introduction to Programming", difficulty: "medium", type: "mcq", en: "Which of these is a programming language?", hi: "इनमें से कौन सी एक प्रोग्रामिंग भाषा है?", mr: "यापैकी कोणती एक प्रोग्रामिंग भाषा आहे?", options: ["Python", "Photoshop", "PowerPoint", "Windows"], answer: "Python" },
  { subject: "Computer", concept: "Database Basics", chapter: "Databases", difficulty: "hard", type: "mcq", en: "An organized collection of data stored electronically is called a?", hi: "इलेक्ट्रॉनिक रूप से संग्रहीत डेटा के व्यवस्थित संग्रह को क्या कहते हैं?", mr: "इलेक्ट्रॉनिक पद्धतीने साठवलेल्या माहितीच्या व्यवस्थित संग्रहाला काय म्हणतात?", options: ["Database", "Spreadsheet", "Browser", "Firewall"], answer: "Database" },
  { subject: "Computer", concept: "Cyber Security", chapter: "Cyber Safety", difficulty: "medium", type: "mcq_multi", en: "Which of these are good cyber-safety habits? (Select all that apply)", hi: "इनमें से कौन सी अच्छी साइबर-सुरक्षा आदतें हैं? (सभी सही विकल्प चुनें)", mr: "यापैकी कोणत्या चांगल्या सायबर-सुरक्षा सवयी आहेत? (सर्व योग्य पर्याय निवडा)", options: ["Using strong passwords", "Sharing your password with friends", "Not clicking unknown links", "Logging out of shared devices"], answers: ["Using strong passwords", "Not clicking unknown links", "Logging out of shared devices"] },
  { subject: "Computer", concept: "HTML Basics", chapter: "Web Basics", difficulty: "medium", type: "mcq", en: "HTML is mainly used to create?", hi: "HTML का उपयोग मुख्य रूप से किसे बनाने के लिए किया जाता है?", mr: "HTML चा वापर प्रामुख्याने काय तयार करण्यासाठी होतो?", options: ["Web pages", "Spreadsheets", "Videos", "Operating systems"], answer: "Web pages" },
  { subject: "Computer", concept: "AI Awareness", chapter: "Introduction to AI", difficulty: "basic", type: "mcq", en: "Which of these is an example of Artificial Intelligence in daily life?", hi: "रोज़मर्रा की ज़िंदगी में इनमें से कौन आर्टिफिशियल इंटेलिजेंस का उदाहरण है?", mr: "दैनंदिन जीवनात यापैकी कोणतं आर्टिफिशियल इंटेलिजन्सचं उदाहरण आहे?", options: ["Voice assistants like Siri/Alexa", "A regular calculator", "A pencil", "A wall clock"], answer: "Voice assistants like Siri/Alexa" }
];

function chapterList(mcqs) { return [...new Set(mcqs.map(q => q.chapter))]; }

function buildStandard(mcqBank) {
  return { likert: SECTION_A_LIKERT, behaviour: sectionB(chapterList(mcqBank)), ai: SECTION_C_AI, text: SECTION_E_TEXT, mcq: mcqBank };
}

const QUESTION_BANK = { "8": buildStandard(MCQ_8), "9": buildStandard(MCQ_9), "10": buildStandard(MCQ_10) };
